This is our notebook for our preliminary data cleaning and logistic regression model.

In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
from dateutil import parser
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import Lasso
from sklearn.linear_model import SGDClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from datetime import datetime as DAMN
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report



In [2]:
df = pd.read_csv("crime.csv")
df.shape

(902298, 19)

In [3]:
df.drop(['Unnamed: 0', 'Block', 'Beat', 'X Coordinate', 'Y Coordinate', 'Latitude', 'Longitude', 'Ward', 'Community Area'], inplace=True, axis=1)

In [4]:
df[:100]

Primary Type                  Description  \
0               ASSAULT                       SIMPLE   
1               ASSAULT                       SIMPLE   
2               BATTERY      DOMESTIC BATTERY SIMPLE   
3         OTHER OFFENSE             TELEPHONE THREAT   
4                 THEFT               $500 AND UNDER   
5       CRIMINAL DAMAGE                  TO PROPERTY   
6     CRIMINAL TRESPASS            TO STATE SUP LAND   
7               BATTERY      DOMESTIC BATTERY SIMPLE   
8               BATTERY      DOMESTIC BATTERY SIMPLE   
9     CRIMINAL TRESPASS            TO STATE SUP LAND   
10      CRIMINAL DAMAGE                   TO VEHICLE   
11             BURGLARY               FORCIBLE ENTRY   
12        OTHER OFFENSE  VIOLATE ORDER OF PROTECTION   
13              BATTERY      DOMESTIC BATTERY SIMPLE   
14                THEFT                ATTEMPT THEFT   
15  MOTOR VEHICLE THEFT                   AUTOMOBILE   
16        OTHER OFFENSE             TELEPHONE THREAT   
17      CRIMINAL DAMAGE                  TO PROPERTY   
18                THEFT               $500 AND UNDER   
19              BATTERY                       SIMPLE   
20                THEFT               $500 AND UNDER   
21              BATTERY      DOMESTIC BATTERY SIMPLE   
22              ASSAULT                       SIMPLE   
23             BURGLARY               UNLAWFUL ENTRY   
24             BURGLARY               FORCIBLE ENTRY   
25              BATTERY      DOMESTIC BATTERY SIMPLE   
26              BATTERY      DOMESTIC BATTERY SIMPLE   
27      CRIMINAL DAMAGE  TO CITY OF CHICAGO PROPERTY   
28          SEX OFFENSE             PUBLIC INDECENCY   
29              BATTERY                       SIMPLE   
..                  ...                          ...   
70                THEFT                ATTEMPT THEFT   
71    CRIMINAL TRESPASS                      TO LAND   
72        OTHER OFFENSE            LICENSE VIOLATION   
73      CRIMINAL DAMAGE  TO CITY OF CHICAGO PROPERTY   
74             BURGLARY               FORCIBLE ENTRY   
75                THEFT                 RETAIL THEFT   
76             BURGLARY               FORCIBLE ENTRY   
77        OTHER OFFENSE             TELEPHONE THREAT   
78                THEFT               $500 AND UNDER   
79        OTHER OFFENSE             TELEPHONE THREAT   
80        OTHER OFFENSE             PAROLE VIOLATION   
81                THEFT                    OVER $500   
82              ASSAULT                       SIMPLE   
83    CRIMINAL TRESPASS                      TO LAND   
84              BATTERY                       SIMPLE   
85             BURGLARY               FORCIBLE ENTRY   
86  MOTOR VEHICLE THEFT                   AUTOMOBILE   
87        OTHER OFFENSE             PAROLE VIOLATION   
88                THEFT                FROM BUILDING   
89             BURGLARY               FORCIBLE ENTRY   
90      CRIMINAL DAMAGE                   TO VEHICLE   
91                THEFT               $500 AND UNDER   
92              ROBBERY               ARMED: HANDGUN   
93                THEFT                 RETAIL THEFT   
94                THEFT                FROM BUILDING   
95        OTHER OFFENSE      HARASSMENT BY TELEPHONE   
96              BATTERY                       SIMPLE   
97              ROBBERY               ARMED: HANDGUN   
98              ASSAULT                       SIMPLE   
99              BATTERY      DOMESTIC BATTERY SIMPLE   

                              Location Description  Arrest  Domestic  \
0                   PARKING LOT/GARAGE(NON.RESID.)       0         0   
1                                        APARTMENT       0         1   
2                                        RESIDENCE       0         1   
3                                        APARTMENT       0         0   
4                                          TAXICAB       0         0   
5                                        APARTMENT       0         0   
6   AIRPORT TERMINAL LOWER LEVEL -

In [5]:
# One Hot Encoded (Categorical Data)
df = pd.get_dummies(df, columns =['Primary Type', 'Description', 'Location Description', 'District'])

In [6]:
df[:100]

Arrest  Domestic      sin_hour  cos_hour  sin_month     cos_month  \
0        0         0  7.847643e-15       1.0        1.0  6.123234e-17   
1        0         1  7.847643e-15       1.0        1.0  6.123234e-17   
2        0         1  7.847643e-15       1.0        1.0  6.123234e-17   
3        0         0  7.847643e-15       1.0        1.0  6.123234e-17   
4        0         0  7.847643e-15       1.0        1.0  6.123234e-17   
5        0         0  7.847643e-15       1.0        1.0  6.123234e-17   
6        1         0  7.847643e-15       1.0        1.0  6.123234e-17   
7        0         1  7.847643e-15       1.0        1.0  6.123234e-17   
8        1         0  7.847643e-15       1.0        1.0  6.123234e-17   
9        1         0  7.847643e-15       1.0        1.0  6.123234e-17   
10       0         0  7.847643e-15       1.0        1.0  6.123234e-17   
11       0         0  7.847643e-15       1.0        1.0  6.123234e-17   
12       0         1  7.847643e-15       1.0        1.0  6.123234e-17   
13       0         1  7.847643e-15       1.0        1.0  6.123234e-17   
14       1         0  7.847643e-15       1.0        1.0  6.123234e-17   
15       0         0  7.847643e-15       1.0        1.0  6.123234e-17   
16       0         1  7.847643e-15       1.0        1.0  6.123234e-17   
17       0         1  7.847643e-15       1.0        1.0  6.123234e-17   
18       0         0  7.847643e-15       1.0        1.0  6.123234e-17   
19       0         0  7.847643e-15       1.0        1.0  6.123234e-17   
20       0         0  7.847643e-15       1.0        1.0  6.123234e-17   
21       0         1  7.847643e-15       1.0        1.0  6.123234e-17   
22       0         0  7.847643e-15       1.0        1.0  6.123234e-17   
23       0         0  7.847643e-15       1.0        1.0  6.123234e-17   
24       0         0  7.847643e-15       1.0        1.0  6.123234e-17   
25       0         1  7.847643e-15       1.0        1.0  6.123234e-17   
26       0         1  7.847643e-15       1.0        1.0  6.123234e-17   
27       0         0  7.847643e-15       1.0        1.0  6.123234e-17   
28       0         0  7.847643e-15       1.0        1.0  6.123234e-17   
29       0         0  7.847643e-15       1.0        1.0  6.123234e-17   
..     ...       ...           ...       ...        ...           ...   
70       1         0  7.847643e-15       1.0        1.0  6.123234e-17   
71       1         0  7.847643e-15       1.0        1.0  6.123234e-17   
72       0         0  7.847643e-15       1.0        1.0  6.123234e-17   
73       0         0  7.847643e-15       1.0        1.0  6.123234e-17   
74       0         0  7.847643e-15       1.0        1.0  6.123234e-17   
75       1         0  7.847643e-15       1.0        1.0  6.123234e-17   
76       0         0  7.847643e-15       1.0        1.0  6.123234e-17   
77       0         0  7.847643e-15       1.0        1.0  6.123234e-17   
78       0         0  7.847643e-15       1.0        1.0  6.123234e-17   
79       0         0  7.847643e-15       1.0        1.0  6.123234e-17   
80       1         0  7.847643e-15       1.0        1.0  6.123234e-17   
81       0         0  7.847643e-15       1.0        1.0  6.123234e-17   
82       0         0  7.847643e-15       1.0        1.0  6.123234e-17   
83       1         0  7.847643e-15       1.0        1.0  6.123234e-17   
84       1         0  7.847643e-15       1.0        1.0  6.123234e-17   
85       0         0  7.847643e-15       1.0        1.0  6.123234e-17   
86       0         0  7.847643e-15       1.0        1.0  6.123234e-17   
87       1         0  7.847643e-15       1.0        1.0  6.123234e-17   
88       0         0  7.847643e-15       1.0        1.0  6.123234e-17   
89       0         0  7.847643e-15       1.0        1.0  6.123234e-17   
90       0         0  7.847643e-15       1.0        1.0  6.123234e-17   
91       0         0  7.847643e-15       1.0        1.0  6.123234e-17   
92       0         0  7.847643e-15       1.0        1.0  6.123

In [7]:
y = df["Arrest"].copy(True)
X = df.drop(['Arrest'], axis=1).copy(True)

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, random_state = DAMN.now().second)

/Users/reubenrappaport/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_split.py:2010: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


In [9]:
df.shape

(902298, 467)

In [10]:
X_train.shape

(721838, 466)

In [11]:
X_test.shape

(180460, 466)

In [12]:
y_train.shape

(721838,)

In [13]:
y_test.shape

(180460,)

In [14]:
classifier = GaussianNB()

In [15]:
y_pred = classifier.fit(X_train, y_train).predict(X_test)
confusion_matrix_result = confusion_matrix(y_test, y_pred)
print(confusion_matrix_result)

[[137497  11158]
 [ 15653  16152]]


In [16]:
classifier.score(X_test, y_test)

0.85142967970741434

In [17]:
print(classification_report(y_test, y_pred))

             precision    recall  f1-score   support

          0       0.90      0.92      0.91    148655
          1       0.59      0.51      0.55     31805

avg / total       0.84      0.85      0.85    180460



In [18]:
classifier2 = SGDClassifier(loss='hinge', penalty='l1')

/Users/reubenrappaport/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:84: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)


In [19]:
y_pred2 = classifier2.fit(X_train, y_train).predict(X_test)
conf_mat2 = confusion_matrix(y_test, y_pred2)
print(conf_mat2)

[[145081   3574]
 [ 19376  12429]]


In [20]:
classifier2.score(X_test, y_test)

0.87282500277069708

In [21]:
print(classification_report(y_test, y_pred2))

             precision    recall  f1-score   support

          0       0.88      0.98      0.93    148655
          1       0.78      0.39      0.52     31805

avg / total       0.86      0.87      0.86    180460



In [23]:
classifier3 = DecisionTreeClassifier(random_state=DAMN.now().second)

In [24]:
y_pred3 = classifier3.fit(X_train, y_train).predict(X_test)
conf_mat3 = confusion_matrix(y_test, y_pred3)
print(conf_mat3)

[[139763   8892]
 [ 17611  14194]]


In [26]:
classifier3.score(X_test, y_test)

0.85313642912556797

In [27]:
print(classification_report(y_test, y_pred3))

             precision    recall  f1-score   support

          0       0.89      0.94      0.91    148655
          1       0.61      0.45      0.52     31805

avg / total       0.84      0.85      0.84    180460

